name: Brahmastra_Fast_Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git openjdk-17-jdk
          pip3 install --user --upgrade buildozer cython==0.29.36 virtualenv
      - name: Build
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Seedha build, koi extra command nahi
          yes | buildozer android debug
          find . -name "*.apk" -exec cp {} ./brahmastra.apk \;
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Brahmastra-Light
          path: brahmastra.apk

